######################## default configuration ####################
baseURL = "/"
title = "Filecoin Security"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "UA-52930282-10"



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
# category = "categories"
# tag = "tags"
# author = "author"

############################## navigation ###############################

[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "Responsible Disclosure"
URL = "responsible-disclosure"
weight = 2

[[menu.main]]
name = "Audits"
URL = "https://spec.filecoin.io/#section-appendix.audit_reports.audit-reports"
weight = 2

[[menu.main]]
name = "Bug Bounty"
URL = "bug-bounty"
weight = 3

[[menu.main]]
name = "Security Updates"
URL = "updates"
weight = 4

[[menu.main]]
name = "Leaderboard"
URL = "thanks"
weight = 5

#################### default parameters ################################
[params]
# Meta data
description = "Filecoin Security Program"
author = "The Filecoin Project"

# cookies
[params.cookies]
enable = true
expire_days = 30

# banner
[params.banner]
image = "images/2020-landscape-1-2.jpg"

# footer
[params.footer]
title = "Filecoin Security"
content = "The Filecoin Security program is part of the The Filecoin project. It encourages responsible vulnerability research and disclosure."

github = "[filecoin-project Org on on GitHub](https://github.com/filecoin-project)"
spec = "[Specification of the Filecoin protocol](https://spec.filecoin.io)"

copyright = "[Filecoin](https://filecoin.io)"

############################# social site ########################
[params.social]
github = "https://github.com/filecoin-project"
slack = "https://filecoin.io/slack"
twitter = "https://twitter.com/Filecoin"
email = "security@filecoin.org"
