######################## default configuration ####################
baseURL = "/"
title = "Filecoin Security"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "UA-52930282-10" 



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
# category = "categories"
# tag = "tags"
# author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "Bug Bounty"
URL = "bugbounty"
weight = 2

[[menu.main]]
name = "Security Updates"
URL = "security/updates"
weight = 3

[[menu.main]]
name = "Disclosure Policy"
URL = "security/disclosure-policy"
weight = 4

[[menu.main]]
name = "Response Process"
URL = "security/response-process"
weight = 4


#################### default parameters ################################
[params]
# Meta data
description = "Filecoin Bug Bounty Program"
author = "The Filecoin Project"

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = ""

para1 = "Having a vibrant community of security researchers auditing Filecoin and its dependencies is at the core of building a robust platform, mitigating risks and building trust in the Filecoin ecosystem."

para2 = "We invite security researchers acting in good faith to help us maintain a high standard of security."

image = "images/2020-landscape-1-2.png"

# blog
[params.blog]

# call to action
[params.call_to_action]
enable = true
title = "Bug Bounty"
content = "Reported security vulnerabilities are eligible for a Bug Bounty. We invite community members and bug bounty hunters to help find bugs and improve our protocol and node implementations."
button_label = "Bug Bounty Program"
button_url = "bugbounty"

# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item ]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item ]]
image = "images/2020-square-1.png"


# footer
[params.footer]
title = "About This Site"
content = "The Filecoin project encourages responsible vulnerability research and disclosure. This site describes our definition of good faith in the context of finding and reporting vulnerabilities, our security procedure and bug bounty program."

github = "[Filecoin-project on Github](https://github.com/filecoin-project)"
spec = "[Filecoin Specification](https://spec.filecoin.io/)"

copyright = "[Filecoin](https://filecoin.io)"

############################# social site ########################
[params.social]
github = "https://github.com/filecoin-project"
slack = "https://filecoin.io/slack"
twitter = "https://twitter.com/Filecoin"
email = "security@filecoin.org"

